Tell how to write IO plugins in the IO plugin chapter.
radareorg/radare2-book pull request #349
Opened 2022-08-15 14:38 UTC by gogo2464

**Checklist**

- [ ] Closing issues: #issue
- [X] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [X] I wrote some documentation

**Description**

2022-08-15 20:33 UTC, trufae requested changes

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +An example of how to write a plugin is avaible in this commit: [here](https://github.com/radareorg/radare2/pull/20574/commits/f9abd3026c37961a485656447eff7bff616322bf).
```suggestion
An example of how to write a plugin is available in this commit: [here](https://github.com/radareorg/radare2/pull/20574/commits/f9abd3026c37961a485656447eff7bff616322bf).
```

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +I/Write r2 IO plugin with Makefile (for Linux only)
I/write? What do you mean here?

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +```
```suggestion
```Makefile
```

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +```
```suggestion
```c
```

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +III/Insert the plugin in radare2
Use ## titles or ### and use 1) instead of roman numbers. Look more readable to me

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +This tutorial has been based on [this one by Wensel](https://wenzel.github.io/2018/04/15/radare2-io-plugin-tutorial.html).
```suggestion
This tutorial is based on [this one by Wensel](https://wenzel.github.io/2018/04/15/radare2-io-plugin-tutorial.html).
```

2022-08-15 20:33 UTC, trufae commented on src/plugins/ioplugins.md
> +```
```suggestion
```c
```

2022-08-24 10:47 UTC, gogo2464 commented
@trufae sounds ready to merge.

2022-08-24 23:17 UTC, trufae commented
Thanks for the reminder. Yes lgtm. But it will be good if the code snippets could follow the coding style guideliness. There are missing braces, missing spaces, unnecessary comments.. im fine to merge it like this. There are probably other code snippets that dont match in the book.

can you do this fix quick before i merge? Thanks!

2022-09-16 07:43 UTC, merged

2022-09-16 07:43 UTC, trufae commented
Ill fix the indents